tunnel: 12a3fedd-2a1a-4d60-9e77-20851faa9faa
credentials-file: /home/nonroot/.cloudflared/12a3fedd-2a1a-4d60-9e77-20851faa9faa.json
ingress:
  - hostname: bot1.melnikovbot.ru
    service: http://nginx:80
  - service: http_status:404
